# Generated by Django 6.1.1 on 2026-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wire',
            name='fromId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wire',
            name='fromSide',
            field=models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='wire',
            name='toId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wire',
            name='toSide',
            field=models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
